### ISSUE TITLE
lldpcli inventory: what help do you need?

### ISSUE THREAD

**Issue by FlorianHeigl** [seppovic/check_mk-plugins#10]
Hi,

in the TODO section you got this time:

## TODO

* extract Agentplugin from mk_inventory.sh as used in our environment lldpcli -f keyvalue show neighbors 2>/dev/null

I'd love to do it but I don't understand what you're meaning, exactly.
You can find me via Twitter (@florianheigl1) or on IRC/freenet: darkfader in #check_mk

**Comment by seppovic** [comment]
Hey Florian,
sorry for the late reply. didnt see the mail notification from github :/
Actually i dont know what i wanted to do back then. But i guess my intention was to extract that command from our modified mk_inventory.sh script and put it in an own file to make it packageable.

**Comment by seppovic** [comment]
That's approximately our patch btw.
```
--- /usr/lib/check_mk_agent/plugins/mk_inventory.orig	2019-03-11 23:07:52.993169704 +0100
+++ /usr/lib/check_mk_agent/plugins/mk_inventory	2017-12-18 22:15:44.000000000 +0100
@@ -103,4 +103,9 @@
         puppet config --section agent print environment
     fi
 
+    if type /usr/sbin/lldpcli >/dev/null ; then
+        echo "<<<lldp:persist($UNTIL)>>>"
+        lldpcli -f keyvalue show neighbors 2>/dev/null
+    fi
+
 fi
```

**Comment by FlorianHeigl** [comment]
Hi,

I got it working fine. One thing I noticed is that since the original LLDP plugin is also using a ```<<<lldp>>>``` section but the format is different, you got some problem if you want SNMP (switches) and these. At least it seemed like it.
I ended up renaming this one to ```<<<linux_lldp>>>``` and Max's stayed ```<<<lldp>>>``` .

Both of course *can* write to ```networking.lldp``` in the inventory.

Anyway, I'll close this since the TODO isn't really anything TODO ;-)

**Comment by seppovic** [comment]
sure, it makes sense to stay out of a already ocupied namespace.
do you think it would break a lot of installations if i switch to <<<linux_lldp>>> ?
...not much into cmk anymore :/

**Comment by FlorianHeigl** [comment]
Hey,

## update

honestly, just bump "the version" of the package with a clear log entry.
Yesterday I was on the phone with someone who said "but Solaris", so soon enough there's also be a ```<<<solaris_lldp>>>```.
What would happen for people if you rename is that they find the inventory gets stale / disappears, then they look, see there's an updated package or a new version here in the repo, adjust, move on.
Plus, the linux side was mostly "build it yourself" due to the mk_inventory patch. I think it's OK and easy to fix.

## inv tree

Since the version I'm actually using in a few places has diverged from this one
(since I make it write to same variable names and inventory namespace as Max's and no GUI part (since we got that from there as soon as the names match))

Would you be OK if I release that separately (with a link here)?
