### ISSUE TITLE
testssl: Error creating configuration: 'testssl' 

### ISSUE THREAD

**Issue by ClaudioLiRanzi** [seppovic/check_mk-plugins#13]
Hi, 

I'm trying to enable the testssl check in my CheckMK environment. Currently there isn't an mkp file available, so I tried to integrate the check manually. When I try to configure the check for a service I always get the following message when activating the check:

Failed: Error creating configuration: 'testssl' 

Normally I would suspect an associated file under "~ / share / check_mk / checks /" but in the case of testssl I'm not sure. Is it possible that I'm missing somthing or is it just my fault because of misconfiguration? 

Regards,

Claudio

**Comment by seppovic** [comment]
Hey Claudio,

the testssl check is not finished and probably never will, I simply don't find the time to code on it.
And as I am not into monitoring at $work I try to support all the working plugins as good as i can, but new development is not going on.
