### ISSUE TITLE
package install problem on  check_mk version 1.2.6

### ISSUE THREAD

**Issue by jweglinski** [seppovic/check_mk-plugins#5]
Hello!
package jolokia_generic-2.2.3.mkp is not installing on check_mk 1.2.6 due to file conflict with base check_mk installation:

`#cmk -V`
`This is check_mk version 1.2.6`

`#cmk -P list`
`check_mk`

`#cmk -P install jolokia_generic-2.2.3.mkp`
`File conflict: /usr/share/check_mk/agents/cfg_examples/jolokia.cfg is part of another package.`

regards,
J. Weglinski

**Comment by seppovic** [comment]
Good Morning  jweglinski,

i cant confirm this bug with cmk enterprise version 1.2.6p3 

```
$ su - testsiteJolokia 
$ cmk -P list

$ cmk -V
This is check_mk version 1.2.6p3
$ cmk -P install /tmp/jolokia_generic-2.2.3.mkp 
$ cmk -P list
jolokia_generic
```

**Comment by jweglinski** [comment]
I am using Check_MK Raw Edition (CRE) and two files are common between check_mk and jolokia_generic packages:

`#cmk -P list jolokia_generic-2.2.3.mkp > /tmp/jolokia.list`
`#cmk -P list check_mk > /tmp/check_mk.list`
`#cat /tmp/check_mk.list /tmp/jolokia.list  | sort | uniq -d`
`/usr/share/check_mk/agents/cfg_examples/jolokia.cfg`
`/usr/share/check_mk/agents/plugins/mk_jolokia`

is there a possibility to install it as package or should I deploy individual files?

regards,
J. Weglinski

**Comment by seppovic** [comment]
I have no real expirience with raw edition. but i guess you can either have check_mk package or jolokia_generic package. 
but you can of course untar the mkp and its files, and move them into you monitoring site. you could also repackage them afterwards, to make it deployable in your setup.

btw. what is that check_mk package for? and where is it from?

**Comment by jweglinski** [comment]
Hello!
it seems that check_mk package is the main check_mk installation - no modules were installed so far and contents looks like check_mk distribution (from package listing):
2999 files, including:
/usr/share/check_mk/checks/ibm_svc_systemstats
/usr/share/check_mk/checks/ibm_xraid_pdisks
/usr/share/check_mk/checks/if
/usr/share/check_mk/checks/if64
/usr/share/check_mk/checks/if64_tplink
/usr/share/check_mk/checks/if_brocade
/usr/share/check_mk/checks/if.include
/usr/share/check_mk/checks/if_lancom
/usr/share/check_mk/checks/netif
/usr/share/check_mk/checks/netstat
/usr/share/check_mk/checks/netstat.include
/usr/share/check_mk/checks/network_fs.include
/usr/share/check_mk/checks/nfsexports
/usr/share/check_mk/checks/nfsmounts
/usr/share/doc/check_mk/checks/cisco_asa_failover
/usr/share/doc/check_mk/checks/cisco_cpu
/usr/share/doc/check_mk/checks/cisco_fan
/usr/share/doc/check_mk/checks/cisco_fantray
/usr/share/doc/check_mk/checks/cisco_fru_power
/usr/share/doc/check_mk/checks/cisco_hsrp
/usr/share/doc/check_mk/checks/cisco_mem
/usr/share/doc/check_mk/checks/cisco_power
/usr/share/doc/check_mk/checks/cisco_qos
/usr/share/doc/check_mk/checks/cisco_secure
/usr/share/doc/check_mk/checks/cisco_sys_mem
/usr/share/doc/check_mk/checks/cisco_temp
/usr/share/doc/check_mk/checks/cisco_temperature
/usr/share/check_mk/agents/check-mk-agent_1.2.6-1_all.deb
/usr/share/check_mk/agents/check-mk-agent-1.2.6-1.noarch.rpm
/usr/share/check_mk/agents/check_mk_agent.aix
/usr/share/check_mk/agents/check_mk_agent.freebsd
/usr/share/check_mk/agents/check_mk_agent.hpux
/usr/share/check_mk/agents/check_mk_agent.linux
/usr/share/check_mk/agents/check_mk_agent.macosx
/usr/share/check_mk/agents/check_mk_agent.netbsd
/usr/share/check_mk/agents/check_mk_agent.openbsd
/usr/share/check_mk/agents/check_mk_agent.openvms
/usr/share/check_mk/agents/check_mk_agent.solaris
/usr/share/check_mk/agents/check-mk-agent.spec
/usr/share/check_mk/web/htdocs/userdb.py
/usr/share/check_mk/web/htdocs/crashed_check.py
/usr/share/check_mk/web/htdocs/bi.py
/usr/share/check_mk/web/htdocs/login.css
/usr/share/check_mk/web/htdocs/weblib.py
/usr/share/check_mk/web/htdocs/logwatch.css
/usr/share/check_mk/pnp-templates/check_mk_active-disk_smb.php
/usr/share/check_mk/pnp-templates/check_mk_active-http.php
/usr/share/check_mk/pnp-templates/check_mk_active-icmp.php
/usr/share/check_mk/pnp-templates/check_mk_active-mail_loop.php
/usr/share/check_mk/pnp-templates/check_mk_active-mail.php
/usr/share/doc/check_mk/livestatus/api/python/livestatus.py
/usr/share/doc/check_mk/livestatus/api/python/example_multisite.py
/usr/share/doc/check_mk/livestatus/api/python/example.py
/usr/share/doc/check_mk/livestatus/api/python/README

regards,
J. Weglinski

**Comment by seppovic** [comment]
actually, there is not much i can do here i guess. 
closing this issue
